name: Update plots

on:
  schedule:
    # run at 16:30 (German time zone) on every day-of-week from Monday through Friday.
    - cron: '30 14 * * 1-5'

jobs:
  staging:
    name: Update plots
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache python dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-python-deps
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ env.cache-name }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ env.cache-name }}-
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Update plots & push to repository
        run: |
          sudo locale-gen de_DE.UTF-8
          sudo update-locale LANG=de_DE.UTF-8

          python convert_ODMS_file_to_timeseries.py
          python plot_data.py

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update plots $(date -I)"
          git push origin master
